### ISSUE TITLE
Dates aren't sortable

### ISSUE THREAD

**Issue by mpiecyk** [admirhodzic/FathGrid#1]
First of all, thank you for this high-performance and both lightweight and feature-rich data grid!

It appears dates aren't sortable. You can repro in your demo by trying to sort the DOB column in demos/sample.html. I also can't get dates to sort in my website. Interestingly, even when I changed the type of the column from date to text, it still wouldn't sort (like the other text columns), maybe because somehow the yyyy-MM-dd format we're using is causing the issue to repro.

**Comment by admirhodzic** [comment]
Thanks!
Sort by date column should be OK now.
