### ISSUE TITLE
How to enable onclick event for a column?

### ISSUE THREAD

**Issue by pranky89** [admirhodzic/FathGrid#10]
For example, I have a column ERROR ID, on clicking which, I would like to either open a popup or show a modal with more information about that error, how can I do that ?

**Comment by admirhodzic** [comment]
You can define onClick function in config object:

 

{

onClick: function(rownumber, columnIndex, TDelement) { alert(‘You clicked on ‘+columnIndex+’ column’) },

…

}

 

 

 

From: pranky89 ***@***.***> 
Sent: Thursday, June 24, 2021 3:16 AM
To: admirhodzic/FathGrid ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [admirhodzic/FathGrid] How to enable onclick event for a column? (#10)

 

For example, I have a column ERROR ID, on clicking which, I would like to either open a popup or show a modal with more information about that error, how can I do that ?

**Comment by pranky89** [comment]
sorry, dumb question, How do i get the values for rownumber, columnIndex, TDelement ?

**Comment by admirhodzic** [comment]
Those values are provided to your function as parameters.

 

…

onClick: 

function(rowNumber, columnIndex, tdElement)

{

//access values in variables “rowNumber”, “columnIndex” or “tdElement”

 

console.log(“you clicked on: “, rowNumber, columnIndex, tdElement);

}

…

**Comment by pranky89** [comment]
got it, this is working great. Thanks
