### ISSUE TITLE
Header Authorization with refresh token

### ISSUE THREAD

**Issue by nazakar** [admirhodzic/FathGrid#14]
Hi I'm using
fetchOptions: {
    headers: {
      'Authorization' : "Bearer " + Token,
    }
but when token expired and i generated a new token, Authorization is with old token .Where pass new generate token? How to handle this problem? 
Thank You

**Comment by admirhodzic** [comment]
Hi,
You can use 
.setConfig({fetchOptions:{...}})

**Comment by nazakar** [comment]
Hi again, i made function that calls refresh-token on expire:     
onInitTable : function(tbody){
        if  ( localStorage.getItem("exp") <= new Date()/1000) {
            fetch('<?=$apiurl?>auth/refresh-token', {
              method: 'POST',
              body: JSON.stringify('<?=$rt?>'),
              headers: {
                'Content-Type': 'application/json',
              },
            }).then(res => res.json())
              .then(res => {
              localStorage.setItem('token', res.token.value);
              localStorage.setItem('exp', res.token.expiresAt);
              console.log(res);
              t1.setConfig({fetchOptions:
                  {
                      headers: {
                          'Authorization' : "Bearer " + res.token.value,
                      }
                  }
              });
            })
        }
    }
if I use for example pagination often  /after 30-40secons/ onInitTable works, but if i load page and let page for a minute, and go to next page for example,  I'm getting console error "error getting data: TypeError: data is undefined" .Can you help me please?
Thank You
