### ISSUE TITLE
Unquoted numbers from a JavaScript array table input cannot be filtered

### ISSUE THREAD

**Issue by mpiecyk** [admirhodzic/FathGrid#2]
In your demo demos/sample.html, currently, if you try to specify any ID in the filter bar, it finds no results. The bug only repros when the number in the JavaScript array table input is unquoted. There is a workaround of putting all numbers in double quotes and then filtering works, but it would be nice to not need to do that and save a little bit of bandwidth.

**Comment by admirhodzic** [comment]
It is fixed in commit 28e50ca

**Comment by mpiecyk** [comment]
Thanks so much for the fast fixes!
