### ISSUE TITLE
Authorization Header

### ISSUE THREAD

**Issue by nazakar** [admirhodzic/FathGrid#4]
How to set Authorization Header in serverUrl?

**Comment by admirhodzic** [comment]
set fetchOptions in config object to something like:
```
{
  headers: {
    'Authorization' : 'Bearer '+mytoken
  }
}
```

example:

```
t1=FathGrid("table1",{
  serverURL:'https://jsonplaceholder.typicode.com/posts?_page=${page}&_limit=${size}&_sort=${sort}&_order=${order}&q=${search}&${filters}',
  fetchOptions: {
    headers: {
      'Authorization' : 'Bearer '+mytoken
    }
  }
});

```

**Comment by nazakar** [comment]
Thank you for your response. I connected with my API, but how pass  parameters for pagination like in example  _page=${page} 
How to get ${page}? In my api it is in meta key response

**Comment by admirhodzic** [comment]
How do you ask for second page with your API?

If it is a query parameter, for example, “pageNumber”, use in serverUrl: “…?pageNumber={page}”
