### ISSUE TITLE
Html column on click trigger event

### ISSUE THREAD

**Issue by nazakar** [admirhodzic/FathGrid#5]
Hi, I have column
  html:x=>`<a id="view_${x.id}" class="btn btn-warning btn-xs view1"   data-id="${x.id}" ><i class="fa fa-file"></i></a>`,
This is button , i want on click event to open modal window for view or update selected record.
My js is:
    $('.view1').click(function (){
    $.get($(this).attr('href'), function(data) {

      $('#view-modal').modal('show')
          .find('.modal-body').html(data)
    })
    return false;
    });
click function not triggers
Can you help me?
Thank you

**Comment by admirhodzic** [comment]
Hi,

You should put your click event-binding code in onInitTable function.

“onInitTable(tbody)” is called after table content is refreshed. 

 

Example:

T1=FathGrid(“mytable”,{

…

onInitTable : function(tbody){

$('.view1').click(function (){
$.get($(this).attr('href'), function(data) {

  $('#view-modal').modal('show')
      .find('.modal-body').html(data)
})
return false;
});

 

},

…

})

 

From: nazakar ***@***.***> 
Sent: utorak, 30. mart 2021. 14:31
To: admirhodzic/FathGrid ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [admirhodzic/FathGrid] Html column on click trigger event (#5)

 

Hi, I have column
html:x=><a id="view_${x.id}" class="btn btn-warning btn-xs view1" data-id="${x.id}" ><i class="fa fa-file"></i></a>,
This is button , i want on click event to open modal window for view or update selected record.
My js is:
$('.view1').click(function (){
$.get($(this).attr('href'), function(data) {

  $('#view-modal').modal('show')
      .find('.modal-body').html(data)
})
return false;
});

click function not triggers
Can you help me?
Thank you

**Comment by nazakar** [comment]
Thank you very much! FathGrid is great  and very useful !!!

**Comment by admirhodzic** [comment]
Thanks
