### ISSUE TITLE
How can I groupBy value

### ISSUE THREAD

**Issue by aemonge** [admirhodzic/FathGrid#8]
I have a list of tasks in the grid, rendering the name, ID and status.

I would like to count/group all the tasks that are "completed" status. how can I do this ?

Thanks in advance

**Comment by admirhodzic** [comment]
Just add something like this in FathGrid config:

 

      sortBy : [1],//group on first column

      groupOn : item=>`${item[0]}`, //group expression

      showGroupFooter : true,

 

Regards,

 

From: Andres Monge ***@***.***> 
Sent: Thursday, May 13, 2021 6:09 PM
To: admirhodzic/FathGrid ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [admirhodzic/FathGrid] How can I groupBy value (#8)

 

I have a list of tasks in the grid, rendering the name, ID and status.

I would like to count/group all the tasks that are "completed" status. how can I do this ?

Thanks in advance

**Comment by aemonge** [comment]
Can you provide with some examples; I can't reproduce it on my case.

**Comment by aemonge** [comment]
Never mind, I finally got it !!

Though, if I might suggest, I would appreciate a demo for the grouping with none numeric keys ;)
